services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_gateway
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5432:5432"

  api:
    build: ./backend
    container_name: gateway_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://gateway_user:gateway_pass@postgres:5432/payment_gateway
    depends_on:
      - postgres

  dashboard:
    build: ./frontend
    container_name: gateway_dashboard
    ports:
      - "3000:80"

  checkout:
    build: ./checkout-page
    container_name: gateway_checkout
    ports:
      - "3001:80"
